package test:test;

interface resource-floats {
  resource my-float {
    constructor(v: f64);
    get: func() -> f64;
  }
}

world test {
  use resource-floats.{my-float};

  export resource-floats-exports: interface {
    resource my-float {
      constructor(v: f64);
      get: func() -> f64;
      add: static func(a: my-float, b: f64) -> my-float;
    }
  }

  import resource-floats-imports: interface {
    resource my-float {
      constructor(v: f64);
      get: func() -> f64;
      add: static func(a: my-float, b: f64) -> my-float;
    }
  }

  export add: func(a: borrow<my-float>, b: borrow<my-float>) -> own<my-float>;
}
