package local:rename-interface;

interface foo {
  record bar {
    dummy: bool
  }
}

world the-world {
  import foo;
  import other-name: interface {
    use foo.{bar};

    a: func() -> bar;
  }
}
