interface chars {
  /// A function that returns a character
  return-char: func() -> char
  /// A function that accepts a character
  take-char: func(x: char)
}

default world the-world {
  import imports: self.chars
  export exports: self.chars
}
